// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgF-R-cdXHjFv5rTCyFTpkpVGgRn4WxAs',
    appId: '1:375276128027:web:57e1bc10d19e5f172275be',
    messagingSenderId: '375276128027',
    projectId: 'b2b-connect-defa7',
    authDomain: 'b2b-connect-defa7.firebaseapp.com',
    storageBucket: 'b2b-connect-defa7.appspot.com',
    measurementId: 'G-GDWZ8W1LGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoK0NCCnrHo045NIRWtDpsayVmVkX4hqc',
    appId: '1:375276128027:android:d44e2ba5e2fa99752275be',
    messagingSenderId: '375276128027',
    projectId: 'b2b-connect-defa7',
    storageBucket: 'b2b-connect-defa7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBOGWKStHxGadog_Wb7MLuERQ7JcJ_HLQ',
    appId: '1:375276128027:ios:d2ab6f71aa7913cc2275be',
    messagingSenderId: '375276128027',
    projectId: 'b2b-connect-defa7',
    storageBucket: 'b2b-connect-defa7.appspot.com',
    androidClientId: '375276128027-vso3jg08j6m2jpnqbi1d30bop7lqtl67.apps.googleusercontent.com',
    iosClientId: '375276128027-tqp5f6fefdkf89hhptprmvuql48a23he.apps.googleusercontent.com',
    iosBundleId: 'com.example.b2bConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBOGWKStHxGadog_Wb7MLuERQ7JcJ_HLQ',
    appId: '1:375276128027:ios:d2ab6f71aa7913cc2275be',
    messagingSenderId: '375276128027',
    projectId: 'b2b-connect-defa7',
    storageBucket: 'b2b-connect-defa7.appspot.com',
    androidClientId: '375276128027-vso3jg08j6m2jpnqbi1d30bop7lqtl67.apps.googleusercontent.com',
    iosClientId: '375276128027-tqp5f6fefdkf89hhptprmvuql48a23he.apps.googleusercontent.com',
    iosBundleId: 'com.example.b2bConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgF-R-cdXHjFv5rTCyFTpkpVGgRn4WxAs',
    appId: '1:375276128027:web:8e94b9a2f117de0b2275be',
    messagingSenderId: '375276128027',
    projectId: 'b2b-connect-defa7',
    authDomain: 'b2b-connect-defa7.firebaseapp.com',
    storageBucket: 'b2b-connect-defa7.appspot.com',
    measurementId: 'G-R9E2GMJBWP',
  );
}
